version: '3'
services:
  miniconda-requirements-jupyter-notebook-server:
    build:
      context: ./miniconda-requirements-jupyter
    ports:
      - 8888:8888
    volumes:
      - ../.:/project_working_directory/shared_volume
    environment:
      - SHELL=/bin/bash
    command: jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root
